name: traderplugin
version: '1.0-SNAPSHOT'
main: lordostrov.traderplugin.Traderplugin
api-version: '1.20'

commands:
  buy:
    description:
      permission:
      usage: /<command> <coin>

  menu:
    description:
      permission:
      usage: /<command>